import Head from "next/head";
import React from "react";
import EcommerceSection1 from "../components/ecommerce/ecommerce-sectio1";
import EcommerceSection2 from "../components/ecommerce/ecommerce-section2";
import EcommerceSection3 from "../components/ecommerce/ecommerce-section3";
import Layout from "../components/globalUi/Layout";
import ServicesFooter from "../components/layout/servicesFooter";
import EcommerceSpanish from "../content/es/ecommerce.json";

const Ecommerce = () => {
  const data = EcommerceSpanish;

    return (
        <>
            <Head>
                <title>Desarrollo de ecommerce</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
              <main>
                <EcommerceSection1 data={data.section1}/>
                <EcommerceSection2 data={data.section2}/>
                <EcommerceSection3 data={data.section3}/>
                <ServicesFooter />
              </main>
            </Layout>
        </>
    );
};

export default Ecommerce;
