import Head from "next/head";
import React from "react";
import EcommerceSection1 from "../components/ecommerce/ecommerce-sectio1";
import Layout from "../components/globalUi/Layout";
import ServicesFooter from "../components/layout/servicesFooter";
import EcommerceSpanish from "../content/es/ecommerce.json";

const Ecommerce = () => {
  const data = EcommerceSpanish;

    return (
        <>
            <Head>
                <title>Desarrollo de ecommerce</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
              <main>
                <EcommerceSection1 title={data.section1.title} services={data.section1.services} images={data.section1.images}/>
                
                <ServicesFooter />
              </main>
            </Layout>
        </>
    );
};

export default Ecommerce;
