//nextjs
import Head from 'next/head'
import { useRouter } from 'next/router';
//components
import Layout from '../components/globalUi/Layout'
import Section1 from '../components/home/section1'
import Section2 from '../components/home/section2'
import Section3 from '../components/home/section3'
import Section4 from '../components/home/section4';
import Section5 from '../components/home/section5';
import Section6 from '../components/home/section6';
//content
import HomeEnglish from '../content/en/home.json'
import HomeSpanish from '../content/es/home.json'

export default function Home() {
  const { locale } = useRouter();

  const data = (locale === 'es') ? HomeSpanish : HomeEnglish;


  return (
    <>
      <Head>
        <title>Desarrollo web crespo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main>
          <Section1 data={data.section1}/>
          <Section2 data={data.section2}/>
          <Section3 data={data.section3}/>
          <Section4 data={data.section4}/>
          <Section5 data={data.section5}/>
          {/* <Section6 title={data.section6.title} partners={data.section6.partners} /> */}
        </main>
      </Layout>
    </>
  )
}
