//nextjs
import Head from 'next/head'
import { useRouter } from 'next/router';
//components
import Layout from '../components/globalUi/Layout'
import Section1 from '../components/home/section1'
import Section2 from '../components/home/section2'
import Section3 from '../components/home/section3'
import Section4 from '../components/home/section4';
import Section5 from '../components/home/section5';
import Section6 from '../components/home/section6';
//content
import HomeEnglish from '../content/en/home.json'
import HomeSpanish from '../content/es/home.json'

export default function Home() {
  const { locale } = useRouter();

  const data = (locale === 'es') ? HomeSpanish : HomeEnglish;


  return (
    <>
      <Head>
        <title>Desarrollo web crespo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main>
          <Section1 title={data.section1.title} subtitle={data.section1.subtitle}/>
          <Section2 title={data.section2.title} cta={data.section2.cta}/>
          <Section3 title={data.section3.title} content={data.section3.content} cta={data.section3.cta} image={data.section3.image}/>
          <Section4 title={data.section4.title} content={data.section4.content} services={data.section4.services}/>
          <Section5 title={data.section5.title} techs={data.section5.techs}/>
          <Section6 title={data.section6.title} partners={data.section6.partners} />
        </main>
      </Layout>
    </>
  )
}
