import Head from "next/head";
import React from "react";
import Layout from "../components/globalUi/Layout";
import ServicesFooter from "../components/layout/servicesFooter";

const Web = () => {
    return(
      <>
        <Head>
            <title>Desarrollo de web</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
            <main>
                
                <ServicesFooter />
            </main>
        </Layout>
      </>
    )
};

export default Web;
